# Generated by Django 3.1 on 2020-08-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_auto_20200822_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social_app.activitytracking')),
                ('friend', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_app.users')),
            ],
            bases=('social_app.activitytracking',),
        ),
    ]
