# Generated by Django 3.1 on 2020-08-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
