# Generated by Django 3.1 on 2020-08-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_auto_20200824_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend',
            field=models.CharField(max_length=200),
        ),
    ]
